version: '3.5'
services:
  postgres:
    container_name: postgres-lingua-evo
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=lingua-evo
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=lingua
    volumes:
      - /var/lib/postgresql/lingua-evo/data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "6444:5432"

  lingua-evo:
    container_name: lingua-evo
    build:
      context: .
      args:
        config_file: ${CONFIG:-config.yaml}
    depends_on:
      - postgres
    restart: always

  migration:
    container_name: migration-lingua-evo
    build:
      context: migration
    depends_on:
      - postgres
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - "./migration -cmd up -url lingua:@postgres-lingua-evo:5432/lingua-evo"