openapi: 3.0.3
info:
  title: Lingua Evo
  version: 0.1.3
  description: Lingua Evo - service for learning foreign words
  contact:
    name: Alexander Ugolkov
    email: ugolkov.prog@gmail.com
    url: https://github.com/av-ugolkov/lingua-evo
servers:
  - url: http://localhost:5000
tags:
  - name: auth
    description: Operations about authentication
  - name: user
    description: Operations about user
  - name: dictionary
    description: Operations about dictionary
  - name: vocabulary
    description: Operations about vocabulary
paths:
  /auth/sign_in:
    post:
      tags:
        - auth
      summary: Sign in
      description: Sign in
      operationId: authSignIn
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSessionRq'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSessionRs'          
        '400':
          description: Invalid username/password supplied
        '404':
          description: User not found
        '500':
          description: Server error
      security:
        - petstore_auth:
            - write:pets
            - read:pets
  /dictionary/word/random:
    $ref: ./paths/dict.yaml
components:
  schemas:
    CreateSessionRq:
      type: object
      properties:
        user:
          type: string
          example: usernickname/email
        password:
          type: string
          example: password
        fingerprint:
          type: string
          example: 12345
    CreateSessionRs:
      type: object
      properties:
        access_token:
          type: string
          example: 12345
    ErrorResponse:
      type: object
      properties:
        msg:
          type: string
          example: error message
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT