// Code generated by mockery v2.30.1. DO NOT EDIT.

package word

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	word "github.com/av-ugolkov/lingua-evo/internal/services/word"
)

// repoWord is an autogenerated mock type for the repoWord type
type repoWord struct {
	mock.Mock
}

// AddWord provides a mock function with given fields: ctx, w
func (_m *repoWord) AddWord(ctx context.Context, w *word.Word) (uuid.UUID, error) {
	ret := _m.Called(ctx, w)

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *word.Word) (uuid.UUID, error)); ok {
		return rf(ctx, w)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *word.Word) uuid.UUID); ok {
		r0 = rf(ctx, w)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *word.Word) error); ok {
		r1 = rf(ctx, w)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteWord provides a mock function with given fields: ctx, w
func (_m *repoWord) DeleteWord(ctx context.Context, w *word.Word) (int64, error) {
	ret := _m.Called(ctx, w)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *word.Word) (int64, error)); ok {
		return rf(ctx, w)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *word.Word) int64); ok {
		r0 = rf(ctx, w)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *word.Word) error); ok {
		r1 = rf(ctx, w)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindWords provides a mock function with given fields: ctx, w
func (_m *repoWord) FindWords(ctx context.Context, w *word.Word) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, w)

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *word.Word) ([]uuid.UUID, error)); ok {
		return rf(ctx, w)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *word.Word) []uuid.UUID); ok {
		r0 = rf(ctx, w)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *word.Word) error); ok {
		r1 = rf(ctx, w)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRandomWord provides a mock function with given fields: ctx, w
func (_m *repoWord) GetRandomWord(ctx context.Context, w *word.Word) (*word.Word, error) {
	ret := _m.Called(ctx, w)

	var r0 *word.Word
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *word.Word) (*word.Word, error)); ok {
		return rf(ctx, w)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *word.Word) *word.Word); ok {
		r0 = rf(ctx, w)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*word.Word)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *word.Word) error); ok {
		r1 = rf(ctx, w)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetWord provides a mock function with given fields: ctx, w
func (_m *repoWord) GetWord(ctx context.Context, w *word.Word) (uuid.UUID, error) {
	ret := _m.Called(ctx, w)

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *word.Word) (uuid.UUID, error)); ok {
		return rf(ctx, w)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *word.Word) uuid.UUID); ok {
		r0 = rf(ctx, w)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *word.Word) error); ok {
		r1 = rf(ctx, w)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SharedWord provides a mock function with given fields: ctx, w
func (_m *repoWord) SharedWord(ctx context.Context, w *word.Word) (*word.Word, error) {
	ret := _m.Called(ctx, w)

	var r0 *word.Word
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *word.Word) (*word.Word, error)); ok {
		return rf(ctx, w)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *word.Word) *word.Word); ok {
		r0 = rf(ctx, w)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*word.Word)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *word.Word) error); ok {
		r1 = rf(ctx, w)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateWord provides a mock function with given fields: ctx, w
func (_m *repoWord) UpdateWord(ctx context.Context, w *word.Word) error {
	ret := _m.Called(ctx, w)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *word.Word) error); ok {
		r0 = rf(ctx, w)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newRepoWord creates a new instance of repoWord. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newRepoWord(t interface {
	mock.TestingT
	Cleanup(func())
}) *repoWord {
	mock := &repoWord{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
