version: '3.5'
services:
    redis:
        container_name: redis
        image: redis:7.2.4-alpine
        expose:
            - "6379"
        ports:
            - "6379:6379"
        networks:
            - lingua-evo-local
        entrypoint:
            - "/bin/sh"
            - "-ecx"
            - "redis-server --requirepass itBg40drEvZsw2gbHyp0"

    postgres:
        container_name: postgres
        image: postgres:16.1-alpine3.19
        environment:
            - POSTGRES_DB=pg-lingua-evo
            - POSTGRES_PASSWORD=ib6vACdec2Fmht4lnX153
            - POSTGRES_USER=lingua
        volumes:
            - /var/lib/postgresql/lingua-evo/data:/var/lib/postgresql/data
        expose:
            - "5432"
        ports:
            - "6432:5432"
        networks:
            - lingua-evo-local

    service:
        container_name: service
        build:
            context: ../.
            dockerfile: Dockerfile
            args:
                config_dir: ${CONFIG:-docker}
        depends_on:
            - postgres
        restart: always
        extra_hosts:
            - "host.docker.internal:host-gateway"
        expose:
            - "5000"
        ports:
            - "5000:5000"
        networks:
            - lingua-evo-local

    migration:
        container_name: migration
        build:
            context: ../migration
        depends_on:
            - postgres
            - service
        networks:
            - lingua-evo-local
        entrypoint:
            - "/bin/sh"
            - "-ecx"
            - "./migration -cmd up -url lingua:ib6vACdec2Fmht4lnX153@postgres:5432/pg-lingua-evo?sslmode=disable"

networks:
    lingua-evo-local:
        name: lingua-evo-local