version: '3.5'
services:
  redis:
    container_name: redis-base-dev
    image: redis:7.2.4-alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - lingua-dev
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - "redis-server --requirepass "

  postgres:
    container_name: postgres-base-dev
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_DB=pg-lingua-evo
      - POSTGRES_PASSWORD=
      - POSTGRES_USER=lingua
    volumes:
      - /var/lib/postgresql/lingua-evo-dev/data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "6432:5432"
    networks:
      - lingua-dev

  service:
    container_name: lingua-evo-dev
    build:
      context: ../.
      dockerfile: Dockerfile
      args:
        config_dir: ${CONFIG:-docker/server_config_dev}
    depends_on:
      - postgres
      - redis
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - "5000"
    ports:
      - "5000:5000"
    networks:
      - lingua-dev

  migration:
    container_name: migration-dev
    build:
      context: ../migration
    depends_on:
      - postgres
    networks:
      - lingua-dev
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - "./migration -cmd up -url lingua:@postgres-base-dev:5432/pg-lingua-evo?sslmode=disable"

networks:
  lingua-dev:
    name: lingua-dev