version: '3.5'
services:
    redis:
        container_name: redis-lingua-evo
        image: redis:latest
        expose:
            - "6379"
        ports:
            - "6379:6379"
        networks:
            - lingua-evo-local
        entrypoint:
            - "/bin/sh"
            - "-ecx"
            - "redis-server --requirepass "

    postgres:
        container_name: postgres-lingua-evo
        image: postgres:14.5-alpine3.16
        environment:
            - POSTGRES_DB=pg-lingua-evo
            - POSTGRES_PASSWORD=ib6vACdec2Fmht4lnX153
            - POSTGRES_USER=lingua
        volumes:
            - /var/lib/postgresql/lingua-evo/data:/var/lib/postgresql/data
        expose:
            - "5432"
        ports:
            - "6432:5432"
        networks:
            - lingua-evo-local

    lingua-evo:
        container_name: lingua-evo
        build:
            context: ../.
            dockerfile: Dockerfile
            args:
                config_dir: ${CONFIG:-docker}
        depends_on:
            - postgres
        restart: always
        extra_hosts:
            - "host.docker.internal:host-gateway"
        expose:
            - "5000"
        ports:
            - "5000:5000"
        networks:
            - lingua-evo-local

    migration:
        container_name: migration-lingua-evo
        build:
            context: migration
        depends_on:
            - postgres
            - lingua-evo
        networks:
            - lingua-evo-local
        entrypoint:
            - "/bin/sh"
            - "-ecx"
            - "./migration -cmd up -url lingua:ib6vACdec2Fmht4lnX153@postgres-lingua-evo:5432/pg-lingua-evo?sslmode=disable"

networks:
    lingua-evo-local:
        name: lingua-evo-local