services:
  redis:
    container_name: redis-base-dev
    image: redis:7.2.4-alpine
    expose:
      - '6379'
    ports:
      - '6379:6379'
    networks:
      - lingua-dev
    entrypoint:
      - '/bin/sh'
      - '-ecx'
      - 'redis-server --requirepass itBg40drEvZsw2gbHyp0'

  postgres:
    container_name: postgres-base-dev
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_DB=pg-lingua-evo
      - POSTGRES_PASSWORD=pb6v0CdeN3FmKt4anX1j3
      - POSTGRES_USER=lingua
    volumes:
      - /var/lib/postgresql/lingua-evo-dev/data:/var/lib/postgresql/data
      - type: bind
        source: /home/alex/DockerShareFiles
        target: /home/dump
    expose:
      - '5432'
    ports:
      - '6432:5432'
    networks:
      - lingua-dev

  service:
    container_name: lingua-evo-dev
    image: lingua-evo:${BRANCH:-dev}
    build:
      context: ../.
      dockerfile: Dockerfile
      args:
        config_dir: ${CONFIG:-docker/server_config_dev}
        public_cert: ${CERT:-/home/alex/cert/linguaevo.twc1.net/fullchain.pem}
        private_cert: ${CERT:-/home/alex/cert/linguaevo.twc1.net/privkey.pem}
        epsw: ${EPSW}
        jwts: ${JWTS}
        pg_psw: ${PG_PSW}
        redis_psw: ${REDIS_PSW}
        branch: ${BRANCH}
        commit: ${COMMIT}
      additional_contexts:
        root: /
    volumes:
      - type: bind
        source: /home/alex/DockerShareFiles
        target: /lingua-evo/logs
    depends_on:
      - postgres
      - redis
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    expose:
      - '5000'
    ports:
      - '5000:5000'
    networks:
      - lingua-dev

  migration:
    container_name: migration-dev
    image: migration:${BRANCH:-dev}
    build:
      context: ../migration
    depends_on:
      - postgres
    networks:
      - lingua-dev
    entrypoint:
      - '/bin/sh'
      - '-ecx'
      - './migration -cmd ${CMD:-up} -url lingua:pb6v0CdeN3FmKt4anX1j3@postgres-base-dev:5432/pg-lingua-evo?sslmode=disable'

networks:
  lingua-dev:
    name: lingua-dev
