pprof_debug:
    enable: true
    port: 6060
logger:
    output:
        - console
        - file
    level: info
    server_level: error
ssl:
    enable: true
    path: ./cert
    public: fullchain.pem
    private: privkey.pem
jwt:
    expire_access: 300 #5 min
    expire_refresh: 2592000 #30 days
service:
    port: 5000
    allowed_origins:
        - 'http://linguaevo.twc1.net'
        - 'https://linguaevo.twc1.net'
        - 'http://www.linguaevo.twc1.net/'
        - 'https://www.linguaevo.twc1.net/'
postgres:
    name: pg-lingua-evo
    user: lingua
    host: postgres-base
    port: 5432
    max_conns: 10
    min_conns: 0
    max_conn_life_time: 3600
    max_conn_idle_time: 1800
    health_check_period: 60
    connect_timeout: 5
redis:
    name: redis
    host: redis
    port: 6379
    user: lingua
    db: 0
email:
    address: linguaevo@gmail.com
    host: smtp.gmail.com
    port: 587
kafka:
    enable: false
    host: lingua-kafka
    port: 9091
    topics:
        - user_action
