pprof_debug:
    enable: true
    port: 6060
jwt:
    secret: 54f3sY%v0kzQ
    expire_access: 3600 #60 min
    expire_refresh: 2592000 #30 days
service:
    type: tcp
    port: 5000
    allowed_origins:
        - 'http://89.223.127.122'
        - 'http://linguaevo.twc1.net/'
postgres:
    name: pg-lingua-evo
    user: lingua
    password: pb6v0CdeN3FmKt4anX1j3
    host: postgres-base
    port: 5432
redis:
    name: redis
    host: redis
    port: 6379
    user: lingua
    password: itBg40drEvZsw2gbHyp0
    db: 0
email:
    address: ugolkov.prog@gmail.com
    password: 'rhgd axtv fsrl jnht'
kafka:
    enable: false
    host: lingua-kafka
    port: 9091
    topics:
        - user_action
