pprof_debug:
    enable: true
    port: 6060
logger:
    output:
        - console
        - file
    level: info
    server_level: error
ssl:
    enable: true
    path: ./cert
    public: certificate.crt
    private: private.key
jwt:
    secret: 
    expire_access: 300 #5 min
    expire_refresh: 2592000 #30 days
service:
    type: tcp
    port: 5000
    allowed_origins:
        - 'http://linguaevo.twc1.net'
        - 'https://linguaevo.twc1.net'
        - 'http://www.linguaevo.twc1.net/'
        - 'https://www.linguaevo.twc1.net/'
postgres:
    name: pg-lingua-evo
    user: lingua
    password: 
    host: postgres-base
    port: 5432
redis:
    name: redis
    host: redis
    port: 6379
    user: lingua
    password: 
    db: 0
email:
    address: ugolkov.prog@gmail.com
kafka:
    enable: false
    host: lingua-kafka
    port: 9091
    topics:
        - user_action
