pprof_debug:
    enable: false
    port: 6060
jwt:
    secret: 5tV3so&v5Qzn
    expire_access: 3600 #60 min
    expire_refresh: 2592000 #30 days
service:
    type: tcp
    port: 5000
    allowed_origins:
        - "http://localhost:4173"
        - "http://localhost:5173"
        - "http://localhost:8080"
        - "http://192.168.0.184:8080"
postgres:
    name: pg-lingua-evo
    user: lingua
    password: 
    host: postgres-base
    port: 5432
redis:
    name: redis
    host: redis
    port: 6379
    user: lingua
    password: 
    db: 0
kafka:
    enable: true
    host: lingua-kafka
    port: 9091
    topics:
        - user_action
