pprof_debug:
    enable: false
    port: 6060
jwt:
    secret: 5tV3so&v5Qzn
    expire_access: 3600 #60 min
    expire_refresh: 2592000 #30 days
service:
    type: tcp
    port: 5000
    allowed_origins:
        - "http://77.222.37.98"
postgres:
    name: pg-lingua-evo
    user: lingua
    password: ib6vACdec2Fmht4lnX153
    host: postgres-base
    port: 5432
redis:
    name: redis
    host: redis
    port: 6379
    user: lingua
    password: itBg40drEvZsw2gbHyp0
    db: 0
kafka:
    enable: false
    host: lingua-kafka
    port: 9091
    topics:
        - user_action
