pprof_debug:
    enable: false
    port: 6060
logger:
    output:
        - console
    level: debug
    server_level: debug
ssl:
    enable: false
    path: ./cert
    public: certificate.crt
    private: private.key
jwt:
    secret: 
    expire_access: 300 #5 min
    expire_refresh: 3600 #1 hours
service:
    type: tcp
    port: 5000
    allowed_origins:
        - "http://localhost:5173"
        - "https://localhost:5173"
postgres:
    name: pg-lingua-evo
    user: lingua
    password: 
    host: postgres-base-dev
    port: 5432
redis:
    name: redis
    host: redis
    port: 6379
    user: lingua
    password: 
    db: 0
email:
    address: ugolkov.prog@gmail.com
kafka:
    enable: false
    host: lingua-kafka
    port: 9091
    topics:
        - user_action
