pprof_debug:
    enable: false
    port: 6060
jwt:
    secret: 
    expire_access: 3600 #60 min
    expire_refresh: 2592000 #30 days
service:
    type: tcp
    port: 5000
    allowed_origins:
        - "http://89.223.127.122"
postgres:
    name: pg-lingua-evo
    user: lingua
    password: 
    host: postgres-base
    port: 5432
redis:
    name: redis
    host: redis
    port: 6379
    user: lingua
    password: 
    db: 0
email:
    address: ugolkov.prog@gmail.com
    password: 'rhgd axtv fsrl jnht'
kafka:
    enable: false
    host: lingua-kafka
    port: 9091
    topics:
        - user_action
