pprof_debug:
    enable: false
    port: 6060
jwt:
    secret: 5tV3so&v5Qzn
    expire_access: 60*60
    expire_refresh: 60*60*24*30
service:
    type: tcp
    port: 5000
database:
    name_db: pg-lingua-evo
    user: lingua
    password: 
    host: postgres-lingua-evo
    port: 5432
