pprof_debug:
    enable: false
    port: 6060
logger:
    output:
        - console
    level: debug
    server_level: debug
jwt:
    secret: 54f3sY%v0kzQ
    expire_access: 300 #5 min
    expire_refresh: 3600 #1 hours
service:
    type: tcp
    port: 5000
    allowed_origins:
        - "http://localhost:5173"
        - "http://192.168.0.184:8080"
postgres:
    name: pg-lingua-evo
    user: lingua
    password: pb6v0CdeN3FmKt4anX1j3
    host: postgres-base-dev
    port: 5432
redis:
    name: redis
    host: redis
    port: 6379
    user: lingua
    password: itBg40drEvZsw2gbHyp0
    db: 0
email:
    address: ugolkov.prog@gmail.com
kafka:
    enable: false
    host: lingua-kafka
    port: 9091
    topics:
        - user_action
