pprof_debug:
    enable: false
    port: 6060
jwt:
    secret: 5tV3so&v5Qzn
    expire_access: 600 #60 min
    expire_refresh: 36000 #10 hours
service:
    type: tcp
    port: 5000
    allowed_origins:
        - "http://localhost:5173"
        - "http://192.168.0.184:8080"
postgres:
    name: pg-lingua-evo
    user: lingua
    password: 
    host: postgres-base-dev
    port: 5432
redis:
    name: redis
    host: redis
    port: 6379
    user: lingua
    password: 
    db: 0
email:
    address: ugolkov.prog@gmail.com
    password: 'rhgd axtv fsrl jnht'
kafka:
    enable: false
    host: lingua-kafka
    port: 9091
    topics:
        - user_action
