DROP TABLE IF EXISTS "language" CASCADE;

DROP TABLE IF EXISTS "dictionary" CASCADE;

DROP TABLE IF EXISTS "example" CASCADE;

DROP TABLE IF EXISTS "word" CASCADE;

DROP TABLE IF EXISTS "vocabulary" CASCADE;

DROP TABLE IF EXISTS "users" CASCADE;

DROP TABLE IF EXISTS "tag" CASCADE;