ALTER TABLE IF EXISTS "users"
ADD COLUMN IF NOT EXISTS "max_count_words" BIGINT NOT null default 300;

ALTER TABLE IF EXISTS "users"
ALTER COLUMN "password_hash"
TYPE VARCHAR(255) NOT NULL;

ALTER TABLE IF EXISTS "users"
DROP COLUMN IF EXISTS "google_id" TEXT;

ALTER TABLE IF EXISTS "user_data"
DROP COLUMN IF EXISTS "url_avatar" TEXT NOT NULL DEFAULT '';