pprof_debug:
    enable: true
    port: 6060
jwt:
    secret: $3cr3t
service:
    type: tcp
    port: 5000
database:
    name_db: pg-lingua-evo
    user: lingua
    password: 
    host: localhost
    port: 6432
