pprof_debug:
    enable: true
    port: 6060
jwt:
    secret: 54f3sY%v0kzQ
    expire_access: 600 #10 min
    expire_refresh: 36000 #10 hours
service:
    type: tcp
    port: 5000
    allowed_origins:
        - "http://localhost:5173"
        - "http://192.168.0.184:8080"
postgres:
    name: pg-lingua-evo
    user: lingua
    password: ib6vACdec2Fmht4lnX153
    host: localhost
    port: 6432
redis:
    name: redis-lingua-evo
    host: localhost
    port: 6379
    password: itBg40drEvZsw2gbHyp0
    db: 0
email:
    address: ugolkov.prog@gmail.com
    password: 'rhgd axtv fsrl jnht'
kafka:
    enable: false
    host: lingua-kafka
    port: 9091
    topics:
        - user_action
