is_debug: true
jwt:
    secret: $3cr3t
service:
    type: tcp
    port: 5000
database:
    name_db: pg-lingua-evo
    user: lingua
    password: ib6vACdec2Fmht4lnX153
    host: localhost
    port: 6432
front:
    root: /
web_service:
    url: http://127.0.0.1:5000/api
tlg:
    token: 5762950198:AAHRVBXPgAgrbSv-fUcXeAwbwDysiTXcMtY
    bot_host: api.telegram.org
    batch_size: 100