pprof_debug:
    enable: true
    port: 6060
logger:
    output:
        - console
        - file
    level: info
    server_level: error
jwt:
    secret: 
    expire_access: 300 #5 min
    expire_refresh: 2592000 #30 days
service:
    type: tcp
    port: 5000
    allowed_origins:
        - 'http://89.223.127.122'
        - 'http://linguaevo.twc1.net'
postgres:
    name: pg-lingua-evo
    user: lingua
    password: 
    host: localhost
    port: 6432
redis:
    name: redis-lingua-evo
    host: localhost
    port: 6379
    password: 
    db: 0
email:
    address: ugolkov.prog@gmail.com
kafka:
    enable: false
    host: lingua-kafka
    port: 9091
    topics:
        - user_action
