pprof_debug:
    enable: true
    port: 6060
jwt:
    secret: 5tV3so&v5Qzn
    expire_access: 600 #10 min
    expire_refresh: 2592000 #30 days
service:
    type: tcp
    port: 5000
postgres:
    name: pg-lingua-evo
    user: lingua
    password: ib6vACdec2Fmht4lnX153
    host: localhost
    port: 6432
redis:
    name: redis-lingua-evo
    host: localhost
    port: 6379
    password: 
    db: 0
kafka:
    host: lingua-kafka
    port: 9092
    topic: analytics
