pprof_debug:
    enable: true
    port: 6060
jwt:
    secret: 5tV3so&v5Qzn
    expire_access: 3600 #60 min
    expire_refresh: 2592000 #30 days
service:
    type: tcp
    port: 5000
database:
    name_db: pg-lingua-evo
    user: lingua
    password: 
    host: localhost
    port: 6432
