pprof_debug:
    enable: true
    port: 6060
logger:
    output:
        - console
    level: debug
    server_level: debug
ssl:
    enable: false
    path: /home/alex/cert/linguaevo.twc1.net
    public: certificate.crt
    private: private.key
jwt:
    secret: 
    expire_access: 300 #5 min
    expire_refresh: 2592000 #30 days
service:
    type: tcp
    port: 5000
    allowed_origins:
        - "http://localhost:5173"
        - "https://localhost:5173"
postgres:
    name: pg-lingua-evo
    user: lingua
    password: 
    host: localhost
    port: 6432
    max_conns: 4
    min_conns: 0
    max_conn_lifetime: 3600
    max_conn_idle_time: 1800
    health_check_period: 60
    connect_timeout: 5
redis:
    name: redis-lingua-evo
    host: localhost
    port: 6379
    password: 
    db: 0
email:
    address: ugolkov.prog@gmail.com
kafka:
    enable: false
    host: lingua-kafka
    port: 9091
    topics:
        - user_action
