// Code generated by mockery v2.30.1. DO NOT EDIT.

package service

import (
	events "github.com/av-ugolkov/lingua-evo/internal/services/events"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// mockEventsSvc is an autogenerated mock type for the eventsSvc type
type mockEventsSvc struct {
	mock.Mock
}

// AsyncAddEvent provides a mock function with given fields: uid, payload
func (_m *mockEventsSvc) AsyncAddEvent(uid uuid.UUID, payload events.Payload) {
	_m.Called(uid, payload)
}

// newMockEventsSvc creates a new instance of mockEventsSvc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockEventsSvc(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockEventsSvc {
	mock := &mockEventsSvc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
