// Code generated by mockery v2.30.1. DO NOT EDIT.

package service

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// mockUserSvc is an autogenerated mock type for the userSvc type
type mockUserSvc struct {
	mock.Mock
}

// UserCountWord provides a mock function with given fields: ctx, uid
func (_m *mockUserSvc) UserCountWord(ctx context.Context, uid uuid.UUID) (int, error) {
	ret := _m.Called(ctx, uid)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = rf(ctx, uid)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newMockUserSvc creates a new instance of mockUserSvc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockUserSvc(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockUserSvc {
	mock := &mockUserSvc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
