// Code generated by mockery v2.30.1. DO NOT EDIT.

package dictionary

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockLangSvc is an autogenerated mock type for the langSvc type
type mockLangSvc struct {
	mock.Mock
}

// CheckLanguage provides a mock function with given fields: ctx, langCode
func (_m *mockLangSvc) CheckLanguage(ctx context.Context, langCode string) error {
	ret := _m.Called(ctx, langCode)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, langCode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockLangSvc creates a new instance of mockLangSvc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockLangSvc(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockLangSvc {
	mock := &mockLangSvc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
