name: golangci-lint

on:
  push:
    branches: ["develop"]
jobs:
  golanci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: install golanci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.2
      - name: run lint
        run: make lint 